export const SETTING_VERBS = {
  en: ['set', 'change', 'adjust', 'update', 'autoset', 'auto-set', 'tweak', 'raise', 'increase', 'lower', 'decrease'],
  zh: ['設', '設定', '改', '調', '調整', '提高', '降低', '升到', '降到', '調成', '調成了', '調整為'],
} as const

export const CALIBRATION_KEYWORDS = [
  { key: 'catPresenceThresholdKg', patterns: [/cat\s*presence\s*threshold\s*kg/i, /catPresenceThresholdKg/i, /cat\s*presence\s*threshold/i, /貓咪?重量.*閾值/, /存在閾值/i] },
  { key: 'fsrBaseline', patterns: [/fsr\s*baseline/i, /fsr\s*校正/i, /壓力.*基線/, /重量.*基準/] },
  { key: 'ldrDark', patterns: [/ldr\s*dark/i, /光敏.*暗/i, /光敏.*低值/, /光敏.*下限/] },
  { key: 'ldrBright', patterns: [/ldr\s*bright/i, /光敏.*亮/i, /光敏.*高值/, /光敏.*上限/] },
  { key: 'ultrasonicOffset', patterns: [/ultra(?:sonic)?\s*offset/i, /超音波.*offset/i, /超音波.*偏移/] },
] as const

export const MEMORY_PATTERNS = {
  negative: [
    'do you remember',
    'remember when',
    'remember if',
    'remember whether',
    'can you remember if',
    'can you remember whether',
    'can you remember when',
    'could you remember if',
    'could you remember whether',
    'could you remember when',
    '你記得嗎',
    '你還記得',
    '妳記得',
    '還記得嗎',
    '記得嗎',
  ],
  triggers: [
    '請記住',
    '请记住',
    '幫我記住',
    '帮我记住',
    '請記得',
    '请记得',
    '幫我記得',
    '帮我记得',
    '幫我記下',
    '帮我记下',
    '備忘',
    '备忘',
    '寫下來',
    '寫下',
    '筆記',
    'note this',
    'make a note',
    'save this to memory',
    'save to memory',
    'add to memory',
    'remember that',
    'remember this',
    'remember to',
    'can you remember',
    'could you remember',
    'would you remember',
    'please remember',
    'can u remember',
    'log this',
    'keep this in mind',
  ],
  prefixes: [
    /^(?:請|请)?[您你妳]?記(?:住|得|下)(?:一下|起來|下来)?[:：,\s-]*/i,
    /^(?:幫|帮)[我妳你您]?記(?:住|得|下)(?:一下|起來|下来)?[:：,\s-]*/i,
    /^(?:請|请)?把[這这]?句話?記(?:住|得|下)(?:一下|起來|下来)?[:：,\s-]*/i,
    /^(?:請|请)?備忘[:：,\s-]*/i,
    /^(?:請|请)?寫下(?:來)?[:：,\s-]*/i,
    /^(?:make|keep)\s+(?:a\s+)?note(?:\s+of)?[:：,\s-]*/i,
    /^(?:note|log)\s+(?:this|that)?[:：,\s-]*/i,
    /^save\s+(?:this\s+)?(?:to\s+)?memory[:：,\s-]*/i,
    /^add\s+(?:this\s+)?to\s+memory[:：,\s-]*/i,
    /^remember\s+(?:that|this|to)?[:：,\s-]*/i,
    /^(?:can|could|would|please)\s+(?:you\s+)?(?:please\s+)?remember\s+/i,
  ],
} as const

export const TASK_PATTERNS = {
  intent: [
    /remind\s+(?:me\s+)?to/i,
    /create\s+(?:a\s+)?(?:task|todo)/i,
    /add\s+(?:a\s+)?(?:task|todo)/i,
    /schedule\s+(?:a\s+)?task/i,
    /set\s+(?:a\s+)?reminder/i,
    /任務/,
    /提醒/,
    /待辦/,
    /待办/,
    /新增任務/,
    /建立任務/,
  ],
  categoryHints: [
    { category: 'hydration', patterns: [/喝水|補水|飲水|水碗/i, /hydration/i, /\bwater\b/i] },
    { category: 'nutrition', patterns: [/餵|餌|餐|零食|點心/i, /feed/i, /meal/i, /snack/i, /nutrition/i] },
    { category: 'behavior', patterns: [/玩|互動|陪伴|逗貓|訓練/i, /play/i, /exercise/i, /training/i, /enrich/i, /bond/i] },
    { category: 'wellness', patterns: [/梳|刷|健康|獸醫|保健/i, /groom/i, /vet/i, /wellness/i, /health check/i] },
    { category: 'safety', patterns: [/安全|門窗|電線|危險|檢查/i, /safety/i, /hazard/i, /secure/i] },
    { category: 'maintenance', patterns: [/清潔|打掃|換砂|整理|消毒/i, /clean/i, /litter/i, /sanitize/i, /maintenance/i] },
  ],
} as const

export const CAPABILITY_PATTERNS = {
  pure: [
    'what can you do',
    'what can u do',
    'what can you do for me',
    'can you do anything',
    '你會做什麼',
    '你能做什麼',
    '可以做什麼',
    '會做甚麼',
    '能做什麼',
    '能夠做什麼',
    '功能介紹',
    '介紹功能',
  ],
  proRequest: [
    /professional (advice|suggestion|opinion|mode)/i,
    /professional recommendation/i,
    /professional solution/i,
    /expert (advice|analysis|mode|opinion)/i,
    /expert-level/i,
    /in[-\s]?depth (analysis|explanation|guidance)/i,
    /comprehensive (plan|analysis|report)/i,
    /detailed (plan|analysis|explanation)/i,
    /scientific detail/i,
    /research[-\s]?backed/i,
    /treatment plan/i,
    /medical (advice|guidance|plan)/i,
    /diagnosis/i,
    /clinical/i,
    /veterinarian/i,
    /\bvet\b/i,
    /high precision/i,
    /advanced model/i,
    /pro model/i,
    /better model/i,
    /bigger model/i,
    /smarter model/i,
    /switch (to|on) (the )?(better|pro|bigger|advanced|smarter) model/i,
    /use (the )?(better|pro|bigger|advanced|smarter) model/i,
    /enable (pro|expert) mode/i,
    /activate (pro|expert)/i,
    /專業建議/,
    /專業意見/,
    /專家建議/,
    /專家模式/,
    /更專業/,
    /詳(細|盡)方案/,
    /深入分析/,
    /高階模型/,
    /進階模型/,
    /更強的?模型/,
    /更大的?模型/,
    /智慧模型/,
    /切換.*模型/,
    /啟用.*模型/,
    /大型模型/,
    /高精度/,
    /醫療(建議|方案|評估)/,
    /獸醫/,
    /診斷/,
    /治療/,
    /病情/,
    /健康評估/,
  ],
  manualSwitch: {
    pro: [
      /\bpro\s+mode\b/i,
      /\buse\s+the\s+pro\s+model\b/i,
      /\bswitch\s+to\s+pro\b/i,
      /\benable\s+(?:the\s+)?pro\b/i,
      /\badvanced\s+mode\b/i,
      /\bexpert\s+mode\b/i,
      /專業模式/,
      /切換.*專業/,
      /進階模式/,
      /高階模式/,
    ],
    standard: [
      /\bnormal\s+mode\b/i,
      /\bstandard\s+mode\b/i,
      /\buse\s+the\s+standard\b/i,
      /\bswitch\s+to\s+standard\b/i,
      /\bdisable\s+pro\b/i,
      /\bno\s+pro\b/i,
      /\bbasic\s+mode\b/i,
      /一般模式/,
      /標準模式/,
      /恢復.*標準/,
      /不要.*進階/,
      /關閉.*專業/,
    ],
  },
} as const
